/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
    export interface GlobalComponents {
        ElAside: typeof import("element-plus/es")["ElAside"]
        ElContainer: typeof import("element-plus/es")["ElContainer"]
        ElIcon: typeof import("element-plus/es")["ElIcon"]
        ElIconLocation: typeof import("@element-plus/icons-vue")["Location"]
        ElMain: typeof import("element-plus/es")["ElMain"]
        ElMenu: typeof import("element-plus/es")["ElMenu"]
        ElMenuItem: typeof import("element-plus/es")["ElMenuItem"]
        ElMenuItemGroup: typeof import("element-plus/es")["ElMenuItemGroup"]
        ElRadioButton: typeof import("element-plus/es")["ElRadioButton"]
        ElRadioGroup: typeof import("element-plus/es")["ElRadioGroup"]
        ElSubMenu: typeof import("element-plus/es")["ElSubMenu"]
        HelloWorld: typeof import("./src/components/HelloWorld.vue")["default"]
        RouterLink: typeof import("vue-router")["RouterLink"]
        RouterView: typeof import("vue-router")["RouterView"]
    }
}
